---
- hosts: webserver
  become: yes
  gather_facts: yes
  
  vars:
    # Hostname do servidor
    srv_hostname: jenkins
    # Adicione o IP do seu servidor ou o domínio do site (caso já esteja publicado)
    # Após o provisionamento você poderá acessar o endereço para acessar a página web
    domain_site:  ec2-52-87-186-247.compute-1.amazonaws.com 

  roles:
    - provisioning
    - java
    - jenkins
    - php